name: ManhuntPlus
version: '1.3.2.7'
main: net.tutla.manhuntPlus.ManhuntPlus
api-version: '1.21'
authors: [ TutlaMC ]
website: https://tutla.net
permissions:
  permission.node:
    description: "Tutla Permission Node"
    default: op
    children:
      permission.node.child: true
commands:
  compass:
    description: Gives a tracking compass
  manhunt:
    description: Start/stop/set cooldown/prepare
    permission: permission.node
  surround:
    description: Surround a speedrunner with hunters
    permission: permission.node
