name: ManhuntPlus
version: '1.1'
main: net.tutla.manhuntPlus.ManhuntPlus
api-version: '1.21'
authors: [ TutlaMC ]
website: https://tutla.net
permissions:
  permission.node:
    description: "This is a permission node"
    default: op
    children:
      permission.node.child: true
commands:
  compass:
    description: Gives a tracking compass
    usage: /<command> <player>
  twist:
    description: Changes the twist
    usage: /<command> <twist>
    permission: permission.node
  speedrunner:
    description: Add or remove a runner
    usage: /<command> add|remove <player>
    permission: permission.node
  hunter:
    description: Add/remove a hunter
    usage: /<command> add|remove <player>
    permission: permission.node
  manhunt:
    description: Start/stop/set cooldown/prepare
    usage: /<command> start|stop|cooldown|help|prepare
    permission: permission.node
  surround:
    description: Surround a speedrunner with hunters
    usage: /<command> <player>
    permission: permission.node
