name: ManhuntPlus
version: '1.1'
main: net.tutla.manhuntPlus.ManhuntPlus
api-version: '1.21'
authors: [ TutlaMC ]
website: https://tutla.net
commands:
  compass:
    description: Gives a tracking compass
    usage: /<command> <player>
  twist:
    description: Changes the twist
    usage: /challenge
  speedrunner:
    description: Add or remove a runner
    usage: /<command> add|remove <player>
  hunter:
    description: Add/remove a hunter
    usage: /<command> add|remove <player>
  manhunt:
    description: Start/stop/set cooldown
    usage: /<command> start|stop|cooldown|help
